//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpDep.Communication.EmpDepService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecondNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        private EmpDep.Communication.EmpDepService.Department DepartmentField;
        
        private int SalaryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SecondName {
            get {
                return this.SecondNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SecondNameField, value) != true)) {
                    this.SecondNameField = value;
                    this.RaisePropertyChanged("SecondName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public EmpDep.Communication.EmpDepService.Department Department {
            get {
                return this.DepartmentField;
            }
            set {
                if ((this.DepartmentField.Equals(value) != true)) {
                    this.DepartmentField = value;
                    this.RaisePropertyChanged("Department");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int Salary {
            get {
                return this.SalaryField;
            }
            set {
                if ((this.SalaryField.Equals(value) != true)) {
                    this.SalaryField = value;
                    this.RaisePropertyChanged("Salary");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Department", Namespace="http://tempuri.org/")]
    public enum Department : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HR = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IT = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Transport = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sales = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RnD = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Production = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Storage = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Managment = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Security = 9,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmpDepService.EmpDepServiceSoap")]
    public interface EmpDepServiceSoap {
        
        // CODEGEN: Generating message contract since element name LoadResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Load", ReplyAction="*")]
        EmpDep.Communication.EmpDepService.LoadResponse Load(EmpDep.Communication.EmpDepService.LoadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Load", ReplyAction="*")]
        System.Threading.Tasks.Task<EmpDep.Communication.EmpDepService.LoadResponse> LoadAsync(EmpDep.Communication.EmpDepService.LoadRequest request);
        
        // CODEGEN: Generating message contract since element name employee from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        EmpDep.Communication.EmpDepService.AddResponse Add(EmpDep.Communication.EmpDepService.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<EmpDep.Communication.EmpDepService.AddResponse> AddAsync(EmpDep.Communication.EmpDepService.AddRequest request);
        
        // CODEGEN: Generating message contract since element name employee from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        EmpDep.Communication.EmpDepService.UpdateResponse Update(EmpDep.Communication.EmpDepService.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        System.Threading.Tasks.Task<EmpDep.Communication.EmpDepService.UpdateResponse> UpdateAsync(EmpDep.Communication.EmpDepService.UpdateRequest request);
        
        // CODEGEN: Generating message contract since element name employee from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Remove", ReplyAction="*")]
        EmpDep.Communication.EmpDepService.RemoveResponse Remove(EmpDep.Communication.EmpDepService.RemoveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Remove", ReplyAction="*")]
        System.Threading.Tasks.Task<EmpDep.Communication.EmpDepService.RemoveResponse> RemoveAsync(EmpDep.Communication.EmpDepService.RemoveRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Load", Namespace="http://tempuri.org/", Order=0)]
        public EmpDep.Communication.EmpDepService.LoadRequestBody Body;
        
        public LoadRequest() {
        }
        
        public LoadRequest(EmpDep.Communication.EmpDepService.LoadRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class LoadRequestBody {
        
        public LoadRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadResponse", Namespace="http://tempuri.org/", Order=0)]
        public EmpDep.Communication.EmpDepService.LoadResponseBody Body;
        
        public LoadResponse() {
        }
        
        public LoadResponse(EmpDep.Communication.EmpDepService.LoadResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoadResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EmpDep.Communication.EmpDepService.Person[] LoadResult;
        
        public LoadResponseBody() {
        }
        
        public LoadResponseBody(EmpDep.Communication.EmpDepService.Person[] LoadResult) {
            this.LoadResult = LoadResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add", Namespace="http://tempuri.org/", Order=0)]
        public EmpDep.Communication.EmpDepService.AddRequestBody Body;
        
        public AddRequest() {
        }
        
        public AddRequest(EmpDep.Communication.EmpDepService.AddRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EmpDep.Communication.EmpDepService.Person employee;
        
        public AddRequestBody() {
        }
        
        public AddRequestBody(EmpDep.Communication.EmpDepService.Person employee) {
            this.employee = employee;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddResponse", Namespace="http://tempuri.org/", Order=0)]
        public EmpDep.Communication.EmpDepService.AddResponseBody Body;
        
        public AddResponse() {
        }
        
        public AddResponse(EmpDep.Communication.EmpDepService.AddResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddResult;
        
        public AddResponseBody() {
        }
        
        public AddResponseBody(int AddResult) {
            this.AddResult = AddResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update", Namespace="http://tempuri.org/", Order=0)]
        public EmpDep.Communication.EmpDepService.UpdateRequestBody Body;
        
        public UpdateRequest() {
        }
        
        public UpdateRequest(EmpDep.Communication.EmpDepService.UpdateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EmpDep.Communication.EmpDepService.Person employee;
        
        public UpdateRequestBody() {
        }
        
        public UpdateRequestBody(EmpDep.Communication.EmpDepService.Person employee) {
            this.employee = employee;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateResponse", Namespace="http://tempuri.org/", Order=0)]
        public EmpDep.Communication.EmpDepService.UpdateResponseBody Body;
        
        public UpdateResponse() {
        }
        
        public UpdateResponse(EmpDep.Communication.EmpDepService.UpdateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UpdateResult;
        
        public UpdateResponseBody() {
        }
        
        public UpdateResponseBody(int UpdateResult) {
            this.UpdateResult = UpdateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Remove", Namespace="http://tempuri.org/", Order=0)]
        public EmpDep.Communication.EmpDepService.RemoveRequestBody Body;
        
        public RemoveRequest() {
        }
        
        public RemoveRequest(EmpDep.Communication.EmpDepService.RemoveRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RemoveRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EmpDep.Communication.EmpDepService.Person employee;
        
        public RemoveRequestBody() {
        }
        
        public RemoveRequestBody(EmpDep.Communication.EmpDepService.Person employee) {
            this.employee = employee;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveResponse", Namespace="http://tempuri.org/", Order=0)]
        public EmpDep.Communication.EmpDepService.RemoveResponseBody Body;
        
        public RemoveResponse() {
        }
        
        public RemoveResponse(EmpDep.Communication.EmpDepService.RemoveResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RemoveResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int RemoveResult;
        
        public RemoveResponseBody() {
        }
        
        public RemoveResponseBody(int RemoveResult) {
            this.RemoveResult = RemoveResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EmpDepServiceSoapChannel : EmpDep.Communication.EmpDepService.EmpDepServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmpDepServiceSoapClient : System.ServiceModel.ClientBase<EmpDep.Communication.EmpDepService.EmpDepServiceSoap>, EmpDep.Communication.EmpDepService.EmpDepServiceSoap {
        
        public EmpDepServiceSoapClient() {
        }
        
        public EmpDepServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmpDepServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpDepServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpDepServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmpDep.Communication.EmpDepService.LoadResponse EmpDep.Communication.EmpDepService.EmpDepServiceSoap.Load(EmpDep.Communication.EmpDepService.LoadRequest request) {
            return base.Channel.Load(request);
        }
        
        public EmpDep.Communication.EmpDepService.Person[] Load() {
            EmpDep.Communication.EmpDepService.LoadRequest inValue = new EmpDep.Communication.EmpDepService.LoadRequest();
            inValue.Body = new EmpDep.Communication.EmpDepService.LoadRequestBody();
            EmpDep.Communication.EmpDepService.LoadResponse retVal = ((EmpDep.Communication.EmpDepService.EmpDepServiceSoap)(this)).Load(inValue);
            return retVal.Body.LoadResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmpDep.Communication.EmpDepService.LoadResponse> EmpDep.Communication.EmpDepService.EmpDepServiceSoap.LoadAsync(EmpDep.Communication.EmpDepService.LoadRequest request) {
            return base.Channel.LoadAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmpDep.Communication.EmpDepService.LoadResponse> LoadAsync() {
            EmpDep.Communication.EmpDepService.LoadRequest inValue = new EmpDep.Communication.EmpDepService.LoadRequest();
            inValue.Body = new EmpDep.Communication.EmpDepService.LoadRequestBody();
            return ((EmpDep.Communication.EmpDepService.EmpDepServiceSoap)(this)).LoadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmpDep.Communication.EmpDepService.AddResponse EmpDep.Communication.EmpDepService.EmpDepServiceSoap.Add(EmpDep.Communication.EmpDepService.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public int Add(EmpDep.Communication.EmpDepService.Person employee) {
            EmpDep.Communication.EmpDepService.AddRequest inValue = new EmpDep.Communication.EmpDepService.AddRequest();
            inValue.Body = new EmpDep.Communication.EmpDepService.AddRequestBody();
            inValue.Body.employee = employee;
            EmpDep.Communication.EmpDepService.AddResponse retVal = ((EmpDep.Communication.EmpDepService.EmpDepServiceSoap)(this)).Add(inValue);
            return retVal.Body.AddResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmpDep.Communication.EmpDepService.AddResponse> EmpDep.Communication.EmpDepService.EmpDepServiceSoap.AddAsync(EmpDep.Communication.EmpDepService.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmpDep.Communication.EmpDepService.AddResponse> AddAsync(EmpDep.Communication.EmpDepService.Person employee) {
            EmpDep.Communication.EmpDepService.AddRequest inValue = new EmpDep.Communication.EmpDepService.AddRequest();
            inValue.Body = new EmpDep.Communication.EmpDepService.AddRequestBody();
            inValue.Body.employee = employee;
            return ((EmpDep.Communication.EmpDepService.EmpDepServiceSoap)(this)).AddAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmpDep.Communication.EmpDepService.UpdateResponse EmpDep.Communication.EmpDepService.EmpDepServiceSoap.Update(EmpDep.Communication.EmpDepService.UpdateRequest request) {
            return base.Channel.Update(request);
        }
        
        public int Update(EmpDep.Communication.EmpDepService.Person employee) {
            EmpDep.Communication.EmpDepService.UpdateRequest inValue = new EmpDep.Communication.EmpDepService.UpdateRequest();
            inValue.Body = new EmpDep.Communication.EmpDepService.UpdateRequestBody();
            inValue.Body.employee = employee;
            EmpDep.Communication.EmpDepService.UpdateResponse retVal = ((EmpDep.Communication.EmpDepService.EmpDepServiceSoap)(this)).Update(inValue);
            return retVal.Body.UpdateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmpDep.Communication.EmpDepService.UpdateResponse> EmpDep.Communication.EmpDepService.EmpDepServiceSoap.UpdateAsync(EmpDep.Communication.EmpDepService.UpdateRequest request) {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmpDep.Communication.EmpDepService.UpdateResponse> UpdateAsync(EmpDep.Communication.EmpDepService.Person employee) {
            EmpDep.Communication.EmpDepService.UpdateRequest inValue = new EmpDep.Communication.EmpDepService.UpdateRequest();
            inValue.Body = new EmpDep.Communication.EmpDepService.UpdateRequestBody();
            inValue.Body.employee = employee;
            return ((EmpDep.Communication.EmpDepService.EmpDepServiceSoap)(this)).UpdateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmpDep.Communication.EmpDepService.RemoveResponse EmpDep.Communication.EmpDepService.EmpDepServiceSoap.Remove(EmpDep.Communication.EmpDepService.RemoveRequest request) {
            return base.Channel.Remove(request);
        }
        
        public int Remove(EmpDep.Communication.EmpDepService.Person employee) {
            EmpDep.Communication.EmpDepService.RemoveRequest inValue = new EmpDep.Communication.EmpDepService.RemoveRequest();
            inValue.Body = new EmpDep.Communication.EmpDepService.RemoveRequestBody();
            inValue.Body.employee = employee;
            EmpDep.Communication.EmpDepService.RemoveResponse retVal = ((EmpDep.Communication.EmpDepService.EmpDepServiceSoap)(this)).Remove(inValue);
            return retVal.Body.RemoveResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmpDep.Communication.EmpDepService.RemoveResponse> EmpDep.Communication.EmpDepService.EmpDepServiceSoap.RemoveAsync(EmpDep.Communication.EmpDepService.RemoveRequest request) {
            return base.Channel.RemoveAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmpDep.Communication.EmpDepService.RemoveResponse> RemoveAsync(EmpDep.Communication.EmpDepService.Person employee) {
            EmpDep.Communication.EmpDepService.RemoveRequest inValue = new EmpDep.Communication.EmpDepService.RemoveRequest();
            inValue.Body = new EmpDep.Communication.EmpDepService.RemoveRequestBody();
            inValue.Body.employee = employee;
            return ((EmpDep.Communication.EmpDepService.EmpDepServiceSoap)(this)).RemoveAsync(inValue);
        }
    }
}
